[package]
name = "rust-axum-full-course"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
httpc-test = "0.1.10"
